### ISSUE TITLE
make npm package public?

### ISSUE THREAD

**Issue by hellatan** [1stdibs/eslint-config-1stdibs#6]
any reason NOT to have the npm package public? This repo is already public.

@twhid @robrichard @prestifidibs @antialias @brettjashford @jrdrg @gedas-monginas @nitruxa @nameofname

**Comment by twhid** [comment]
I think it would be cool to go ahead and publish it publicly. I think having our eslint configs public is good from a 1stdibs tech evangelism POV and putting them on npm would only increase exposure.

**Comment by antialias** [comment]
I don't mind

**Comment by hellatan** [comment]
this was done
